openapi: 3.0.3
info:
  title: PACMAN - Catalog Service - OpenAPI 3.0
  version: 1.0.0
servers:
  - url: "http://localhost:8080/api"
tags:
  - name: Products
    description: Catalog products
paths:
  /products:
    get:
      operationId: findProductByCategoryAndMetrics
      tags:
        - Products
      parameters:
        - in: query
          name: category
          description: 'Product category'
          required: true
          schema:
            type: string
            enum:
              - tshirt
        - in: query
          name: metrics
          description: 'List of metrics code'
          required: true
          schema:
            type: array
            items:
              type: string
              enum:
                - sales
                - stock
        - in: query
          name: weights
          description: 'List of metrics weights'
          required: false
          schema:
            type: array
            items:
              type: number
              format: double
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'
        '204':
          description: No content
        '400':
          description: Bad request
components:
  schemas:
    ProductResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string


